greetings = ("Welcome to the Band Name Generator.")
print(greetings)
name_of_city = input("What's the name of the city you grew up in?\n")
name_of_pet = input("What's your pet's name?\n")
print("Your band name could be: " + name_of_city + " " + name_of_pet)
